---
title: "Statistical_Inference1"
author: "Laura Bennett"
date: "May 21, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statistical Inference for Data Science: Chapter 2 Exercises

1. Can you add the probabilities of any two events to get the probability of at least one occuring?
  + **Unless the events are mutually exclusive, you cannot add their individual probabilities to get the probability of at least one occuring.**
  
2. I define a PMF, $p$, so that for $x=0$ and $x=1$ we have $p(0)=-0.1$ and $p(1)=1.1$. Is this a valid PMF?
  + **These are not valid, as probabilities must be between $0$ and $1$.**
  
3. What is hte probability that 75% or fewer calls get answered in a randomly sampled day from the population distribution from this chapter?
  + **The PDF for this particular population is given as $f(x)=2x$ for $0<x<1$; therefore, the probability that 75 or fewer calls are answered is equal to $\int_{0}^{0.75}2x=0.5625$. **

4. The 97.5th percentile of a distribution is what?
  + **The 97.5th percentile of a distribution is the value within a PDF or PMF at which 97.5 percent of the mass of the distribution is below it.**
  
5. Consider influenza epidemics for two parent heterosexual families. Suppose that the probability is 15% that at least one of the parents has contracted the disease. The probability that the father has contracted influenza is 10% while that the mother contracted the disease is 9%. What is the probability that both contracted influeza expressed as a whole number percentage?


  +  $P(Mom \cup Dad)=P(Mom)+P(Dad)-P(Mom\cap Dad)\rightarrow P(Mom\cap Dad)=0.09+0.10-0.15 = 0.04$
  
6. A random variable, $X$, is uniform, a box from 0 to 1 of height 1 (s.t. it's density is $f(x)=1$ for $0<x<1$). What is its median expressed to two decimal places?
  + **The median is the point at which one half of all values are lower than that value; in this case, the median is 0.50. **
  
7. If a continuous density that never touches the horizontal axis is symmetric about zero, can we say that its associated median is zero? 
  + **Yes; half of the area is below zero and half is above, therefore the median is zero. Note, however, that it is important that the curve not sit at the horizontal axis on and around zero, as any number of points within that region of the horizontal axis could then be considered a median. **