---
title: "Statistical_Inference1"
author: "Laura Bennett"
date: "June 2, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statistical Inference for Data Science: Chapter 4 Exercises

1. A standard die takes the values 1:6 with equal probability. What is the expected value?
  + **The expected value of a fair die may be calculated as $E[X]=\sum _x xp(x)=\frac{1}{6}\left(1+2+3+4+5+6 \right )=3.5$**
  
2. Consider a density that is uniform from -1 to 1 (i.e. has height equal to 1/2 and looks like a box starting at -1 and ending at 1). What is the mean of this distribution?
  + **The mean of a continuous probability distribution may be found as $\int p(x)x$. Thus, the mean of this probability density is given as $\int _{-1}^1\frac{1}{2}\cdot x=\left[\frac{1}{4}x^2 \right ]_{-1}^1=\left (\frac{1}{4}-\frac{1}{4} \right )=0$ **
  
3. If a population has a mean $\mu$, what is the mean of the distribution of averages of 20 observations from this distribution?
  + **As you obtain more samples, the mean of the distribution of averages should approach the population mean $\mu$**

4. You are playing a game with a friend where you flip a coin and if it comes up heads you give her $X$ dollars and if it comes up tails she gives you $Y$ dollars. The odds that the coin is heads is $d$. What is your expected earnings?
  + **Given that $E[X]=\sum xp(x)$ and the odds of you winning is given as $d$, your expected earnings may be found as $E[earnings]=Y\left(p \right )-X(1-p)$. Odds is related to probability s.t. $d=\frac{p}{1-p}\rightarrow p=\frac{d}{1+d}$; therefore, your expected earnings is $E[earnings]=Y\left(\frac{d}{1+d} \right )-X\left (1-\frac{d}{1+d}  \right )$**
  
5. If you roll ten standard dice, take their average, and repeat this process over and over and construct a histogram, what would it be centered at?
  +  **As with the single die in question 1, the average of this distribution would be 3.5.**